module: intake_xarray
driver: netcdf
extra_args:
  engine: netcdf4
  chunks: {'time': 1}
root_path: /glade/collections/cmip/cmip5/
activity: output1
institution: NCAR
model: CCSM4
experiment: rcp26
frequency: mon
modeling_realm: atmos 
ensemble_member: r1i1p1
mip_table: Amon
variables:
  - tas
  - ci
  - tasmin
  - ta
  - psl
  - pr
  - tasmax
  - ts